dist: focal
language: python
python:
  - "3.9.7"

install:
  - pip install -r requirements.txt

services:
  - mysql

before_install:
  - if [ $DOGHUB_DB_ENV == "DEV" ]; then DOGHUB_DB_NAME="doghub_dev"; else DOGHUB_DB_NAME="doghub"; fi
  - echo $DOGHUB_DB_ENV
  - echo $DOGHUB_DB_NAME
  - mysql -e "CREATE DATABASE $DOGHUB_DB_NAME;"

before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py loaddata park.yaml
  - python manage.py loaddata tag.yaml

script:
  - python manage.py test
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_script:
  - coveralls

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-west-2"
    app: "django-tutorial"
    env: "doghub-develop-env"
    bucket_name: "elasticbeanstalk-us-west-2-730437625654"
    on:
      repo: gcivil-nyu-org/INET-Monday-Spring2023-Team-1
      branch:
        - develop

  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-west-2"
    app: "django-tutorial"
    env: "doghub-env2"
    bucket_name: "elasticbeanstalk-us-west-2-730437625654"
    on:
      repo: gcivil-nyu-org/INET-Monday-Spring2023-Team-1
      branch:
        - main
