language: python
python:
  - "3.9.7"

install:
  - pip install -r requirements.txt

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE doghub;'

before_script:
  - echo $DOGHUB_DB_ENV
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_script:
  - coveralls

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-west-2"
    app: "django-tutorial"
    env: "doghub-develop-env"
    bucket_name: "elasticbeanstalk-us-west-2-730437625654"
    on:
      repo: gcivil-nyu-org/INET-Monday-Spring2023-Team-1
      branch:
        - develop

  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-west-2"
    app: "doghub-production-env"
    env: "doghub-production-env"
    bucket_name: "elasticbeanstalk-us-west-2-730437625654"
    on:
      repo: gcivil-nyu-org/INET-Monday-Spring2023-Team-1
      branch:
        - main
